[package]
name = "rustblr"
version = "0.1.0"
authors = ["Jon Rosebaugh <jon@inklesspen.com>"]

[dependencies]
hyper = "0.7.2"
url = "0.5.2"
oauth-client = "0.1.1"
curl = "0.2.15"
rand = "0.3.13"
rusqlite = "0.6.0"
clap = "1.5.5"
serde_json = "0.6.0"
